config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  resources :users, only: [:new, :show, :create]
  resources :twits

end

app/models/twit.rb
class Twit < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :twits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def check_for_authorized_user
    unless current_user
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params["user"]["email"])

    if @user && @user.authenticate(params["user"]["password"])
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}", notice: "You Have successfully logged in!"
    else
      redirect_to new_session_path, notice: "You suck, Try again!"
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: "You have successfully logged out"
  end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  def new
    @twit = Twit.new
  end

  def index
    @twits = Twit.all
    @twit = Twit.where params[:user_id]
  end

  def show
    @twit = Twit.find(id: params(:user_id))
  end

  def create
    @twit = Twit.new(twit_params)
    if @twit.save
      @twit.update(user_id: current_user.id)
      redirect_to twits_path
    else
      render :new
    end
  end

  private def twit_params
    params.require("twit").permit(:body)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params["id"])
    @twits = @user.twits
  end

  def create
    @user = User.new
    if @user = User.create(user_params)
      UserMailer.welcome_email(@user).deliver_now
      redirect_to root_path, notice: "Check your email for a confirmation email"
    else
      render :new
    end
  end

  private def user_params
    params.require("user").permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <% if current_user %>
      Welcome, <%= current_user.name %>
      <%= link_to "Log out", logout_path(current_user), method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Log In", new_session_path %>
    <% end %>
    <%= notice %>
    <%= yield %>

  </body>
</html>

app/views/twits/index.html.erb
<h1>The Twits that have been uploaded to our database thus far:</h1>

<% @twits.each do |twit| %>
<p>
  <%= twit.body %>
</p>
<% end %>










<p>
  Back to your page? <%= link_to "Personal Page", user_path(current_user) %>
</p>

app/views/twits/new.html.erb
<%= form_for @twit do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit "Add Twit" %>

  <% end %>

app/views/users/new.html.erb
<h1>Welcome New User please create an account below</h1>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit "Create Account!" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>Welcome: <%= "#{@user.name}" %></h1>
<h3>These are your current twits:</h3><br>

<% @twits.each do |twit| %>
<p>
  <%= twit.body %>
</p>
<% end %><br>
<p>
  Add new Twit? Do so, <%= link_to "Here.", new_twit_path %>
</p>
<p>
  To see all Twits <%= link_to "Click Here", twits_path %>
</p>

<p>
  Tired of this waste of time? logout on the homepage <%= link_to "Here", root_path %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome Twit-not</h1>
<ul>
  <li>
    <p>This is a fake place that really wont post what you want to</p>
    <p>Have a nice day</p>
    <p>If you still care Sign up above.</p>
    <p>If for whatever reason you are an existing user please Sign in above.</p>
  </li>
</ul>